version: '3.3'

services:
  love-letter-frontend:
    container_name: love-letter-frontend
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PORT}:${PORT}